name: Build and Deploy to Azure

on:
  push:
    branches:
      - main  # Ou o nome da branch que deseja usar para deploy

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'  # Altere para a versão do seu .NET

      - name: Restore dependencies
        run: dotnet restore ./Api/ChatbotChallenge.Api/ChatbotChallenge.Api.csproj  # Ajuste o caminho do seu projeto

      - name: Build
        run: dotnet build --configuration Release --no-restore ./Api/ChatbotChallenge.Api/ChatbotChallenge.Api.csproj

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish ./Api/ChatbotChallenge.Api/ChatbotChallenge.Api.csproj

      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'ChatbotChallenge'  # Nome do seu Web App
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Secret que vamos configurar
          package: './publish'
