name: CI/CD for .NET API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore ./Api/ChatbotChallenge.sln

    - name: Build
      run: dotnet build ./Api/ChatbotChallenge.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./Api/ChatbotChallenge.sln --configuration Release --output ./Api/bin/Release/net7.0/publish

    - name: Deploy to Azure Web App
      uses: Azure/webapps-deploy@v2
      with:
        app-name: 'ChatbotChallenge'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Secret que vamos configurar
        package: './Api/bin/Release/net7.0/publish'
